### ISSUE TITLE
[BUG] P2Ball - Game freezes after ad

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#15]
**Describe the bug**
After ad is displayed the game does not regain focus. On desktop clicking the game canvas again will trigger a restart, but on mobile tapping the screen does not restart the game. The player has to change to a different tab or screen then return to trigger a restart.

**Expected behavior**

Game restart should trigger immediately after ad is shown.

**Comment by GroovyWilliam** [comment]
Fix issue in [966701da3765482d66bcc259ac4c8d757edab192](https://github.com/Digital-Will-Inc/html5-games/commit/966701da3765482d66bcc259ac4c8d757edab192)

**Comment by trdillon** [comment]
Issue still persists. After an ad is shown, the player is only able to aim for the next shot. After aiming and releasing, the aim guide disappears but no balls are spawned. The game remains in this state until the player changes tabs or apps.

**Comment by GroovyWilliam** [comment]
Freeze issue can't be replicated easily in Wortal-Prod but I have added a logic to handle focus on the browser as soon as the as the ad finishes.
I have uploaded to [Wortal-Prod](https://html5gameportal.com/developers/2/games/33/e59a1131-40c4-437f-93b3-b445bab2447b/)

I don't want to close this issue yet, but if you can @trdillon to test it on the live version and see if the issue is done.

**Comment by trdillon** [comment]
The latest revision seems to have resolved the issue, thanks.
